version: '3'

volumes:
  static:
  media:
  pg_data:

services:
  database:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikitaraven/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: nikitaraven/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: nikitaraven/foodgram_gateway:latest
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/staticfiles/
      - media:/media/