# Generated by Django 5.1 on 2024-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ingredients', models.ManyToManyField(related_name='shopping_lists', to='recipes.recipeingredient')),
            ],
        ),
    ]
