# Generated by Django 5.1 on 2024-09-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'корзина покупок', 'verbose_name_plural': 'корзины покупок'},
        ),
    ]
